Testing AMI creation with Instance refresh steps

diff --git a/.github/workflows/packer-ami-build.yml b/.github/workflows/packer-ami-build.yml
--- a/.github/workflows/packer-ami-build.yml
+++ b/.github/workflows/packer-ami-build.yml
@@ -114,56 +114,56 @@ jobs:
           packer build --var-file=dev.pkvars.hcl webapp-image.pkr.hcl
 
       
-      # - name: Create a new version of Launch template
-      #   run: |
-      #     AMI_ID=$(aws ec2 describe-images \
-      #       --filters "Name=name,Values=webapp-image-*" \
-      #       --query "Images | sort_by(@, &CreationDate) | [-1].ImageId" \
-      #       --output text)
+      - name: Create a new version of Launch template
+        run: |
+          AMI_ID=$(aws ec2 describe-images \
+            --filters "Name=name,Values=webapp-image-*" \
+            --query "Images | sort_by(@, &CreationDate) | [-1].ImageId" \
+            --output text)
 
-      #       echo "AMI ID: $AMI_ID"
+            echo "AMI ID: $AMI_ID"
 
             
-      #     AWS_PAGER="" aws ec2 create-launch-template-version \
-      #       --launch-template-id ${{ vars.DEMO_LAUNCH_TEMPLATE_ID }} \
-      #       --source-version 1 \
-      #       --launch-template-data '{"ImageId":"'"${AMI_ID}"'"}' \
-      #       --no-paginate \
-      #       --output json
+          AWS_PAGER="" aws ec2 create-launch-template-version \
+            --launch-template-id ${{ vars.DEMO_LAUNCH_TEMPLATE_ID }} \
+            --source-version 1 \
+            --launch-template-data '{"ImageId":"'"${AMI_ID}"'"}' \
+            --no-paginate \
+            --output json
       
   
       
-      # - name: Perform Instance refresh
-      #   run: |
-      #     aws autoscaling start-instance-refresh \
-      #       --auto-scaling-group-name ${{ vars.DEMO_AUTO_SCALING_GROUP_NAME }} \
-      #       --region ${{ secrets.AWS_REGION }} \
-      #       --preferences MinHealthyPercentage=90 \
-      #       --desired-configuration '{"LaunchTemplate": {"LaunchTemplateId": "${{ vars.DEMO_LAUNCH_TEMPLATE_ID }}", "Version": "$Latest"}}' 
+      - name: Perform Instance refresh
+        run: |
+          aws autoscaling start-instance-refresh \
+            --auto-scaling-group-name ${{ vars.DEMO_AUTO_SCALING_GROUP_NAME }} \
+            --region ${{ secrets.AWS_REGION }} \
+            --preferences MinHealthyPercentage=90 \
+            --desired-configuration '{"LaunchTemplate": {"LaunchTemplateId": "${{ vars.DEMO_LAUNCH_TEMPLATE_ID }}", "Version": "$Latest"}}' 
 
-      # - name: Wait for instance refresh to complete
-      #   run: |
-      #     echo "Waiting for instance refresh to complete on ASG: ${{ vars.DEMO_AUTO_SCALING_GROUP_NAME }} "\
+      - name: Wait for instance refresh to complete
+        run: |
+          echo "Waiting for instance refresh to complete on ASG: ${{ vars.DEMO_AUTO_SCALING_GROUP_NAME }} "\
 
-      #     while true; do
-      #         STATUS=$(aws autoscaling describe-instance-refreshes \
-      #         --auto-scaling-group-name ${{ vars.DEMO_AUTO_SCALING_GROUP_NAME }} \
-      #         --query "InstanceRefreshes[0].Status" \
-      #         --output text)
+          while true; do
+              STATUS=$(aws autoscaling describe-instance-refreshes \
+              --auto-scaling-group-name ${{ vars.DEMO_AUTO_SCALING_GROUP_NAME }} \
+              --query "InstanceRefreshes[0].Status" \
+              --output text)
 
-      #       echo "Current status: $STATUS"
+            echo "Current status: $STATUS"
 
-      #       if [ "$STATUS" == "Successful" ]; then
-      #         echo "Instance refresh completed successfully."
-      #         break
-      #       elif [ "$STATUS" == "Cancelled" ] || [ "$STATUS" == "Failed" ]; then
-      #         echo "Instance refresh failed or was cancelled. Status: $STATUS"
-      #         exit 1
-      #       fi
+            if [ "$STATUS" == "Successful" ]; then
+              echo "Instance refresh completed successfully."
+              break
+            elif [ "$STATUS" == "Cancelled" ] || [ "$STATUS" == "Failed" ]; then
+              echo "Instance refresh failed or was cancelled. Status: $STATUS"
+              exit 1
+            fi
 
-      #       echo "Still in progress... checking again in 15 seconds."
-      #       sleep 15
-      #     done
+            echo "Still in progress... checking again in 15 seconds."
+            sleep 15
+          done
 
 
 
